### PR TITLE
chore(security-monkey): Reduced logging level from debug to info

### PR DESCRIPTION
**Pull request by kda-jt**
https://jobteaser.atlassian.net/browse/SIAM-150

### CODE REVIEW

**Review by lerrigatto — APPROVED** [review]
LGTM

**Comment by lerrigatto** [comment]
but your circleci is lacking :D

**Comment by kda-jt** [comment]
> LGTM

Hello @lerrigatto !

**Comment by kda-jt** [comment]
> but your circleci is lacking :D

Yes, sadly :cry:

**Review by rasta-rocket — APPROVED** [review]

**Pull request merged**
